# ──────────────────────────────────────
#  Netlify configuration for DMD-Simulador
# ──────────────────────────────────────

[build]
  # Compila TypeScript a JS optimizado
  command = "npm run build"
  # Sirve la aplicación ya empaquetada
  publish = "dist"

  [build.environment]
    # Fuerza la versión de Node usada en los builds
    NODE_VERSION = "18"

[functions]
  # Carpeta con tus funciones serverless
  directory   = "api"
  node_bundler = "esbuild"

# ─── Redirects ────────────────────────────────────────────────────

# Redirige /api/* a /.netlify/functions/*
[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/:splat"
  status = 200

# Fallback de SPA (Vite) – siempre devuelve index.html
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200

# ─── Global Headers ──────────────────────────────────────────────

# CORS para toda la aplicación
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin  = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"

# Cache estática para configuraciones JSON
[[headers]]
  for = "/config/*"
  [headers.values]
    Cache-Control = "public, max-age=300"

# Cache corta para datos dinámicos
[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=60"
