[build]
  publish = "."

[functions]
  directory = "api"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"

[[headers]]
  for = "/config/*"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=60"